#language
language: android

android:
    components:
        - platform-tools
        - tools

        #used SDK version
        - android-21

        #build tools version
        - build-tools-21.1.2

        #devices
        #android lollipop
        - sys-img-armeabi-v7a-android-21

#integrations
notifications:
  slack: cassetteapp:eeHgRugjn80toSy8b7p9SL6B
